"""empty message

Revision ID: 0efdc9e7a7d1
Revises: 7a4ad2cf1bdc
Create Date: 2022-03-25 11:38:35.095043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efdc9e7a7d1'
down_revision = '7a4ad2cf1bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('familyname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'familyname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
