"""empty message

Revision ID: 95394da5f23a
Revises: 2ba1b6404982
Create Date: 2022-04-04 17:11:01.476680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95394da5f23a'
down_revision = '2ba1b6404982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('car_fail', sa.String(length=200), nullable=True))
    op.add_column('incident', sa.Column('fail_description', sa.String(length=240), nullable=True))
    op.add_column('incident', sa.Column('Vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'incident', 'vehicle', ['Vehicle_id'], ['id'], ondelete='CASCADE')
    op.drop_column('incident', 'name')
    op.drop_column('incident', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('description', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.add_column('incident', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_column('incident', 'Vehicle_id')
    op.drop_column('incident', 'fail_description')
    op.drop_column('incident', 'car_fail')
    # ### end Alembic commands ###
