"""empty message

Revision ID: b4eb39a95790
Revises: e9c0133bd8a1
Create Date: 2022-03-21 11:28:54.452479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eb39a95790'
down_revision = 'e9c0133bd8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('coordinate', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=90), nullable=True),
    sa.Column('picture_incident', sa.String(length=240), nullable=True),
    sa.Column('acces_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acces_id'], ['access.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    # ### end Alembic commands ###
