"""empty message

Revision ID: b95eb5a9c0bd
Revises: 0efdc9e7a7d1
Create Date: 2022-04-04 14:33:40.927984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95eb5a9c0bd'
down_revision = '0efdc9e7a7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
