"""empty message

Revision ID: d714a69cf770
Revises: 829bed13792f
Create Date: 2022-03-21 16:46:21.019170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd714a69cf770'
down_revision = '829bed13792f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('coordinate', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incident', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'incident', 'provider', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_column('incident', 'provider_id')
    op.drop_table('provider')
    # ### end Alembic commands ###
